studiotools:
  name: Studio Tools
  show: false
  env:
    MODE: pub
    PP_JOB_SERVERS: //pp-fs-nyc/production/
    PP_RESOURCE: '%PP_ROOT%'
  versions:
    '1.0':
      path:
        linux: /
        mac: /
        win32: /
aftereffects:
  show: true
  tasks:
  - edit
  - grade
  - conform
  - mix
  versions:
    'CC':
      name: After Effects CC
      env:
        PP_AE: 'CC'
      modes:
        ui:
          linux: /
          mac: /
          win32: ae_pipeline_init.bat
      path:
        linux: /
        mac: /
        win32: '%PP_ROOT%/tools/aftereffects'
    'CC 2014':
      name: After Effects CC 2014
      env:
        PP_AE: 'CC 2014'
      modes:
        ui:
          linux: /
          mac: /
          win32: ae_pipeline_init.bat
      path:
        linux: /
        mac: /
        win32: '%PP_ROOT%/tools/aftereffects'
maya:
  env:
    MAYA_APP_DIR: '%PP_ROOT%/user/%USERNAME%/maya'
    MAYA_PPTOOLS: '%PP_RESOURCE%/tools/maya/common'
    MAYA_PPTOOLS_COMMON: '%PP_RESOURCE%/maya/common'
    MAYA_MODULE_PATH: '%MAYA_PPTOOLS%/modules'
    MAYA_PLUG_IN_PATH: '%MAYA_PPTOOLS%/plugins'
    MAYA_PRESET_PATH: '%MAYA_PPTOOLS%/presets'
    MAYA_SCRIPT_PATH: '%MAYA_PPTOOLS%/scripts'
    MAYA_SHELF_PATH: '%MAYA_PPTOOLS%/shelves'
    XBMLANGPATH: '%MAYA_PPTOOLS%/icons'
    PYTHONPATH: '%PP_RESOURCE%/lib/python;%MAYA_PPTOOLS%/scripts'
  show: true
  versions:
    '2014':
      name: Autodesk Maya 2014
      env:
        PP_MAYA: '2014'
        MAYA_PPTOOLS_VERSIONED: '%PP_RESOURCE%/maya/%PP_MAYA%x64'
        PP_MAYA_DIR: C:/Program Files/Autodesk/Maya%PP_MAYA%
      modes:
        ui:
          linux: /
          mac: /
          win32: maya.exe
      path:
        linux: /
        mac: /
        win32: C:/Program Files/Autodesk/Maya2014/bin
    '2015':
      name: Autodesk Maya
      env:
        MAYA_PPTOOLS_VERSIONED: '%PP_RESOURCE%/maya/%PP_MAYA%x64'
        PP_MAYA: '2015'
        PP_MAYA_DIR: C:/Program Files/Autodesk/Maya%PP_MAYA%
      modes:
        ui:
          linux: /
          mac: /
          win32: maya.exe -noAutoloadPlugins
      path:
        linux: /
        mac: /
        win32: C:/Program Files/Autodesk/Maya2015/bin
  tasks:
  - model
  - shade
  - rig
  - anim
  - effects
  - cloth
  - hair
  - muscle
  - light
softimage:
  env:
    PP_XSI_WORKGRP: '%PP_ROOT%/tools/softimage/common'
    XSI_HOME: '%SI_HOME%'
    XSI_BINDIR: '%XSI_HOME%/Application/bin'
    PYTHONPATH: '%PP_ROOT%/lib/python'
    XSI_PLUGINS: '%PP_ROOT%/tools/softimage/common'
    XSI_USERROOT: '%PP_ROOT%/user/%USERNAME%'
  show: true
  versions:
    '2014':
      name: Autodesk Softimage XSI
      env:
        SI_HOME: 'C:/Program Files/Autodesk/Softimage 2014 SP2/Application/bin'
      modes:
        ui:
          linux: /
          mac: /
          win32:  'xsi.exe'
      path:
        linux: /
        mac: /
        win32: C:/Program Files/Autodesk/Softimage 2014 SP2/Application/bin
    '2015':
      name:  Autodesk Softimage XSI
      env:
        PP_SOFTIMAGE: '2015'
        SI_HOME: 'C:/Program Files/Autodesk/Softimage 2015/Application/bin'
      modes:
        ui:
          linux: /
          mac: /
          win32: 'xsi.exe'
      path:
        linux: /
        mac: /
        win32: C:/Program Files/Autodesk/Softimage 2015/Application/bin
  tasks:
  - model
  - shade
  - rig
  - anim
  - effects
  - cloth
  - hair
  - muscle
  - light
nuke:
  env:
    NUKE_PATH: '%PP_RESOURCE%/tools/nuke'
    NUKE_DISK_CACHE: 'E:/Nuke'
  show: true
  tasks:
  - comp
  - light
  - grade
  - track
  - roto
  versions:
    '7.0v8':
      name: Nuke
      modes:
        ui:
          linux: /
          mac: /
          win32: Nuke7.0.exe
      path:
        linux: /
        mac: /
        win32: C:/Program Files/Nuke7.0v8
    '8.0v5':
      name: Nuke
      modes:
        ui:
          linux: /
          mac: /
          win32: Nuke8.0.exe
      path:
        linux: /
        mac: /
        win32: C:/Program Files/Nuke8.0v5
    '9.0v4':
      name: Nuke
      modes:
        ui:
          linux: /
          mac: /
          win32: Nuke9.0.exe
      path:
        linux: /
        mac: /
        win32: C:/Program Files/Nuke9.0v4
nukex:
  env:
    NUKE_PATH: '%PP_ROOT%/tools/nuke'
    NUKE_DISK_CACHE: 'E:/Nuke'
  show: true
  tasks:
  - comp
  - light
  - grade
  - track
  - roto
  versions:
    '7.0v8':
      name: Nuke
      modes:
        ui:
          linux: /
          mac: /
          win32: Nuke7.0.exe --nukex
      path:
        linux: /
        mac: /
        win32: C:/Program Files/Nuke7.0v8
    '8.0v5':
      name: Nuke
      modes:
        ui:
          linux: /
          mac: /
          win32: Nuke8.0.exe --nukex
      path:
        linux: /
        mac: /
        win32: C:/Program Files/Nuke8.0v5
    '9.0v4':
      name: Nuke
      modes:
        ui:
          linux: /
          mac: /
          win32: Nuke9.0.exe --nukex
      path:
        linux: /
        mac: /
        win32: C:/Program Files/Nuke9.0v4
nukestudio:
  env:
    NUKE_PATH: '%PP_ROOT%/tools/nuke'
    NUKE_DISK_CACHE: 'E:/Nuke'
  show: true
  tasks:
  - comp
  - light
  - grade
  - track
  - roto
  versions:
    '9.0v4':
      name: Nuke
      modes:
        ui:
          linux: /
          mac: /
          win32: Nuke9.0.exe --studio
      path:
        linux: /
        mac: /
        win32: C:/Program Files/Nuke9.0v4
premiere:
  show: true
  tasks:
  - edit
  - grade
  - conform
  - mix
  versions:
    'CC':
      name: Premiere
      modes:
        ui:
          linux: /
          mac: /
          win32: Adobe Premiere Pro.exe
      path:
        linux: /
        mac: /
        win32: C:/Program Files/Adobe/Adobe Premiere Pro CC
    'CC 2014':
      name: Premiere
      modes:
        ui:
          linux: /
          mac: /
          win32: Adobe Premiere Pro.exe
      path:
        linux: /
        mac: /
        win32: C:/Program Files/Adobe/Adobe Premiere Pro CC 2014
hiero:
  name: Hiero
  show: true
  env:
    HIERO_PLUGIN_PATH: '%PP_RESOURCE%/tools/hiero'
  tasks:
  - edit
  - grade
  - conform
  versions:
    '1.7v2':
      modes:
        ui:
          linux: /
          mac: /
          win32: hiero.exe
      path:
        linux: /
        mac: /
        win32: C:/Program Files/The Foundry/Hiero1.7v2
    '1.8v2':
      modes:
        ui:
          linux: /
          mac: /
          win32: hiero.exe
      path:
        linux: /
        mac: /
        win32: C:/Program Files/The Foundry/Hiero1.8v2

motionbuilder:
  name: Mobu
  show: true
  tasks:
  - rig
  - anim
  versions:
    '2014':
      modes:
        ui:
          linux: /
          mac: /
          win32: motionbuilder.exe
      path:
        linux: /
        mac: /
        win32: C:/Program Files/Autodesk/MotionBuilder 2014/bin/x64
photoshop:
  show: true
  tasks:
  - design
  - shade
  - light
  - comp
  versions:
    'CC':
      name: Photoshop CC
      env:
        PP_PS: 'CC'
      modes:
        ui:
          linux: /
          mac: /
          win32: ae_pipeline_init.bat
      path:
        linux: /
        mac: /
        win32: '%PP_ROOT%/tools/aftereffects'
    'CC 2014':
      name: Photoshop CC 2014
      env:
        PP_PS: 'CC 2014'
      modes:
        ui:
          linux: /
          mac: /
          win32: Photoshop.exe
      path:
        linux: /
        mac: /
        win32: 'C:/Program Files/Adobe/Adobe Photoshop CC (64 Bit)'
zbrush:
  show: true
  tasks:
  - design
  - model
  versions:
    '4R6':
      name: ZBrush 4R6
      env:
        PP_ZB: '4R6'
      modes:
        ui:
          linux: /
          mac: /
          win32: ZBrush.exe
      path:
        linux: /
        mac: /
        win32: 'C:/Program Files (x86)/Pixologic/ZBrush 4R6'
mayaAlt:
  env:
    MAYA_APP_DIR: '%PP_ROOT%/user/%USERNAME%/maya'
    MAYA_PPTOOLS: '%PP_RESOURCE%/tools/maya/common'
    MAYA_PPTOOLS_COMMON: '%PP_RESOURCE%/maya/common'
    MAYA_MODULE_PATH: '%MAYA_PPTOOLS%/modules'
    MAYA_PLUG_IN_PATH: '%MAYA_PPTOOLS%/plugins'
    MAYA_PRESET_PATH: '%MAYA_PPTOOLS%/presets'
    MAYA_SCRIPT_PATH: '%MAYA_PPTOOLS%/scripts'
    MAYA_SHELF_PATH: '%MAYA_PPTOOLS%/shelves'
    XBMLANGPATH: '%MAYA_PPTOOLS%/icons'
    PYTHONPATH: '%PP_RESOURCE%/lib/python;%MAYA_PPTOOLS%/scripts'
  show: true
  versions:
    '2014':
      name: Autodesk Maya 2014
      env:
        PP_MAYA: '2014'
        MAYA_PPTOOLS_VERSIONED: '%PP_RESOURCE%/maya/%PP_MAYA%x64'
        PP_MAYA_DIR: C:/Program Files/Autodesk/Maya%PP_MAYA%
      modes:
        ui:
          linux: /
          mac: /
          win32: maya.exe
      path:
        linux: /
        mac: /
        win32: C:/Program Files/Autodesk/Maya2014/bin
    '2015':
      name: Autodesk Maya
      env:
        MAYA_PPTOOLS_VERSIONED: '%PP_RESOURCE%/maya/%PP_MAYA%x64'
        PP_MAYA: '2015'
        PP_MAYA_DIR: C:/Program Files/Autodesk/Maya%PP_MAYA%
      modes:
        ui:
          linux: /
          mac: /
          win32: maya.exe -noAutoloadPlugins
      path:
        linux: /
        mac: /
        win32: C:/Program Files/Autodesk/Maya2015/bin
  tasks:
  - model
  - shade
  - rig
  - anim
  - effects
  - cloth
  - hair
  - muscle
  - light