studiotools:
  name: Studio Tools
  show: false
  env:
    MODE: pub
    ST_JOB_SERVERS: 'C:/Users/aburke/Dropbox/dev/abxStudioDemo'
    ST_RESOURCE: '%ST_ROOT%'
  versions:
    '1.0':
      path:
        linux: /
        mac: /
        win32: /
aftereffects:
  show: true
  tasks:
  - edit
  - grade
  - conform
  - mix
  versions:
    'CC':
      name: After Effects CC
      env:
        ST_AE: 'CC'
      modes:
        ui:
          linux: /
          mac: /
          win32: ae_pipeline_init.bat
      path:
        linux: /
        mac: /
        win32: '%ST_ROOT%/tools/aftereffects'
    'CC 2014':
      name: After Effects CC 2014
      env:
        ST_AE: 'CC 2014'
      modes:
        ui:
          linux: /
          mac: /
          win32: ae_pipeline_init.bat
      path:
        linux: /
        mac: /
        win32: '%ST_ROOT%/tools/aftereffects'
maya:
  env:
    LM_LICENSE_FILE: '@scholar-lic01'
    AUTODESK_ADLM_THINCLIENT_ENV: '//scholar/apps/Autodesk/adlm/AdlmThinClientCustomEnv.xml'
    MAYA_APP_DIR: '%ST_ROOT%/user/%USERNAME%/maya'
    MAYA_STTOOLS: '%ST_RESOURCE%/tools/maya/common'
    MAYA_STTOOLS_COMMON: '%ST_RESOURCE%/maya/common'
    MAYA_MODULE_PATH: '%MAYA_STTOOLS%/modules'
    MAYA_PLUG_IN_PATH: '%MAYA_STTOOLS%/plugins'
    MAYA_PRESET_PATH: '%MAYA_STTOOLS%/presets'
    MAYA_SCRIPT_PATH: '%MAYA_STTOOLS%/scripts'
    MAYA_SHELF_PATH: '%MAYA_STTOOLS%/shelves'
    XBMLANGPATH: '%MAYA_STTOOLS%/icons'
    PYTHONPATH: '%ST_RESOURCE%/lib/python;%MAYA_STTOOLS%/scripts'
  show: true
  versions:
    '2014':
      name: Autodesk Maya 2014
      env:
        ST_MAYA: '2014'
        MAYA_STTOOLS_VERSIONED: '%ST_RESOURCE%/maya/%ST_MAYA%x64'
        ST_MAYA_DIR: C:/Program Files/Autodesk/Maya%ST_MAYA%
      modes:
        ui:
          linux: /
          mac: /
          win32: maya.exe
      path:
        linux: /
        mac: /
        win32: C:/Program Files/Autodesk/Maya2014/bin
    '2015':
      name: Autodesk Maya
      env:
        MAYA_STTOOLS_VERSIONED: '%ST_RESOURCE%/maya/%ST_MAYA%x64'
        ST_MAYA: '2015'
        ST_MAYA_DIR: C:/Program Files/Autodesk/Maya/%ST_MAYA%.0.5
      modes:
        ui:
          linux: /
          mac: /
          win32: maya.exe -noAutoloadPlugins
      path:
        linux: /
        mac: /
        win32: C:/Program Files/Autodesk/Maya/2015.0.5/bin
  tasks:
  - model
  - shade
  - rig
  - anim
  - effects
  - cloth
  - hair
  - muscle
  - light
softimage:
  env:
    ST_XSI_WORKGRP: '%ST_ROOT%/tools/softimage/common'
    XSI_HOME: '%SI_HOME%'
    XSI_BINDIR: '%XSI_HOME%/Application/bin'
    XSI_PLUGINS: '%ST_ROOT%/tools/softimage/common'
  show: true
  versions:
    '2014':
      name: Autodesk Softimage XSI
      env:
        ST_SOFTIMAGE: '2012SP2'
        XSI_PLUGINS: '%ST_ROOT%/tools/softimage/si_2014__sitoa350;%ST_ROOT%/tools/softimage/si_2014__alembic'
        SI_HOME: 'C:/Program Files/Autodesk/Softimage 2014 SP2/Application/bin'
      modes:
        ui:
          linux: /
          mac: /
          win32:  'xsi.exe'
      path:
        linux: /
        mac: /
        win32: C:/Program Files/Autodesk/Softimage 2014 SP2/Application/bin
    '2015':
      name:  Autodesk Softimage XSI
      env:
        ST_SOFTIMAGE: '2015'
        SI_HOME: 'C:/Program Files/Autodesk/Softimage 2015/Application/bin'
      modes:
        ui:
          linux: /
          mac: /
          win32: 'xsi.exe'
      path:
        linux: /
        mac: /
        win32: C:/Program Files/Autodesk/Softimage 2015/Application/bin
  tasks:
  - model
  - shade
  - rig
  - anim
  - effects
  - cloth
  - hair
  - muscle
  - light
nuke:
  env:
    NUKE_PATH: '%ST_RESOURCE%/tools/nuke'
    NUKE_DISK_CACHE: 'C:/Nuke'
    NUKE_TEMP_DIR: 'C:/Nuke/Temp'
  show: true
  tasks:
  - comp
  - light
  - grade
  - track
  - roto
  versions:
    '9.0v7':
      name: Nuke
      modes:
        ui:
          linux: /
          mac: /
          win32: Nuke9.0.exe
      path:
        linux: /
        mac: /
        win32: C:/Program Files/Foundry/Nuke/9.0v7
nukex:
  env:
    NUKE_PATH: '%ST_ROOT%/tools/nuke'
    NUKE_DISK_CACHE: 'C:/Nuke'
    NUKE_TEMP_DIR: 'C:/Nuke/Temp'
  show: true
  tasks:
  - comp
  - light
  - grade
  - track
  - roto
  versions:
    '9.0v7':
      name: Nuke
      modes:
        ui:
          linux: /
          mac: /
          win32: Nuke9.0.exe --nukex
      path:
        linux: /
        mac: /
        win32: C:/Program Files/Foundry/Nuke/9.0v7
nukestudio:
  env:
    NUKE_PATH: '%ST_ROOT%/tools/nuke'
    NUKE_DISK_CACHE: 'C:/Nuke'
    NUKE_TEMP_DIR: 'C:/Nuke/Temp'
  show: true
  tasks:
  - comp
  - light
  - grade
  - track
  - roto
  versions:
    '9.0v7':
      name: Nuke
      modes:
        ui:
          linux: /
          mac: /
          win32: Nuke9.0.exe --studio
      path:
        linux: /
        mac: /
        win32: C:/Program Files/Foundry/Nuke/9.0v7
premiere:
  show: true
  tasks:
  - edit
  - grade
  - conform
  - mix
  versions:
    'CC':
      name: Premiere
      modes:
        ui:
          linux: /
          mac: /
          win32: Adobe Premiere Pro.exe
      path:
        linux: /
        mac: /
        win32: C:/Program Files/Adobe/Adobe Premiere Pro CC
    'CC 2015':
      name: Premiere
      modes:
        ui:
          linux: /
          mac: /
          win32: Adobe Premiere Pro.exe
      path:
        linux: /
        mac: /
        win32: C:/Program Files/Adobe/Adobe Premiere Pro CC 2015
hiero:
  name: Hiero
  show: true
  env:
    HIERO_PLUGIN_PATH: '%ST_RESOURCE%/tools/hiero'
  tasks:
  - edit
  - grade
  - conform
  versions:
    '1.7v2':
      modes:
        ui:
          linux: /
          mac: /
          win32: hiero.exe
      path:
        linux: /
        mac: /
        win32: C:/Program Files/The Foundry/Hiero1.7v2
    '1.8v2':
      modes:
        ui:
          linux: /
          mac: /
          win32: hiero.exe
      path:
        linux: /
        mac: /
        win32: C:/Program Files/The Foundry/Hiero1.8v2

motionbuilder:
  name: Mobu
  show: true
  tasks:
  - rig
  - anim
  versions:
    '2014':
      modes:
        ui:
          linux: /
          mac: /
          win32: motionbuilder.exe
      path:
        linux: /
        mac: /
        win32: C:/Program Files/Autodesk/MotionBuilder 2014/bin/x64
photoshop:
  show: true
  tasks:
  - design
  - shade
  - light
  - comp
  versions:
    'CC':
      name: Photoshop CC
      env:
        ST_PS: 'CC'
      modes:
        ui:
          linux: /
          mac: /
          win32: ae_pipeline_init.bat
      path:
        linux: /
        mac: /
        win32: '%ST_ROOT%/tools/aftereffects'
    'CC 2015':
      name: Photoshop CC 2015
      env:
        ST_PS: 'CC 2015'
      modes:
        ui:
          linux: /
          mac: /
          win32: Photoshop.exe
      path:
        linux: /
        mac: /
        win32: 'C:/Program Files/Adobe/Adobe Photoshop CC 2015'
zbrush:
  show: true
  tasks:
  - design
  - model
  versions:
    '4R6':
      name: ZBrush 4R6
      env:
        ST_ZB: '4R6'
      modes:
        ui:
          linux: /
          mac: /
          win32: ZBrush.exe
      path:
        linux: /
        mac: /
        win32: 'C:/Program Files (x86)/Pixologic/ZBrush 4R6'
mayaAlt:
  env:
    MAYA_APP_DIR: '%ST_ROOT%/user/%USERNAME%/maya'
    MAYA_STTOOLS: '%ST_RESOURCE%/tools/maya/common'
    MAYA_STTOOLS_COMMON: '%ST_RESOURCE%/maya/common'
    MAYA_MODULE_PATH: '%MAYA_STTOOLS%/modules'
    MAYA_PLUG_IN_PATH: '%MAYA_STTOOLS%/plugins'
    MAYA_PRESET_PATH: '%MAYA_STTOOLS%/presets'
    MAYA_SCRIPT_PATH: '%MAYA_STTOOLS%/scripts'
    MAYA_SHELF_PATH: '%MAYA_STTOOLS%/shelves'
    XBMLANGPATH: '%MAYA_STTOOLS%/icons'
    PYTHONPATH: '%ST_RESOURCE%/lib/python;%MAYA_STTOOLS%/scripts'
  show: true
  versions:
    '2014':
      name: Autodesk Maya 2014
      env:
        ST_MAYA: '2014'
        MAYA_STTOOLS_VERSIONED: '%ST_RESOURCE%/maya/%ST_MAYA%x64'
        ST_MAYA_DIR: C:/Program Files/Autodesk/Maya%ST_MAYA%
      modes:
        ui:
          linux: /
          mac: /
          win32: maya.exe
      path:
        linux: /
        mac: /
        win32: C:/Program Files/Autodesk/Maya2014/bin
    '2015':
      name: Autodesk Maya
      env:
        MAYA_STTOOLS_VERSIONED: '%ST_RESOURCE%/maya/%ST_MAYA%x64'
        ST_MAYA: '2015'
        ST_MAYA_DIR: C:/Program Files/Autodesk/Maya/%ST_MAYA%.0.5
      modes:
        ui:
          linux: /
          mac: /
          win32: maya.exe -noAutoloadPlugins
      path:
        linux: /
        mac: /
        win32: C:/Program Files/Autodesk/Maya/2015.0.5/bin
  tasks:
  - model
  - shade
  - rig
  - anim
  - effects
  - cloth
  - hair
  - muscle
  - light