default:
  packages:
    maya:
      version: '2015'
      modules:
        arnold: '1.2.0.8'
        crate: '1.1.145'
        SOuP: '2015'
    softimage:
      version: '2015'
      modules:
        arnold: '3.2.0'
        crate: '1.1.145'
    nuke:
      version: '9.0v5'
    nukex:
      version: '9.0v5'
    nukestudio:
      version: '9.0v5'
    hiero:
      version: '1.8v2'
    aftereffects:
      version: 'CC'
    premiere:
      version: 'CC 2014'
    motionbuilder:
      version: '2014'
    photoshop:
      version: 'CC 2014'
    zbrush:
      version: '4R6'
  order:
  - maya
  - softimage
  - motionbuilder
  - nuke
  - nukex
  - nukestudio
  - hiero
  - aftereffects
  - premiere
  - photoshop
  - zbrush

modeling:
  packages:
    maya:
      version: '2015'
      modules:
        arnold: '1.0.0.4'
        crate: '1.1.145'
    soft:
      version: '2015'
    nuke:
      version: '8.0v5'
    nukex:
      version: '8.0v5'
    hiero:
      version: '1.8v2'

edit:
  packages:
    nuke:
      version: '8.0v5'
    nukex:
      version: '8.0v5'
    hiero:
      version: '1.8v1'
    premiere:
      version: 'CC 2014'

design:
  packages:
    photoshop:
      version: 'CC 2014'
    zbrush:
      version: '4R6'

animation:
  packages:
    maya:
      version: '2015'
      modules:
        arnold: '1.0.0.4'
        crate: '1.1.145'
    softimage:
      version: '2015'
      modules:
        arnold: '3.2.0'
        crate: '1.1.145'
    premiere:
      version: 'CC 2014'