// requires maya "2012";
startAttrPreset( "container" );
blendAttrStr "fileTextureName" "M:/backlot/images/textures/cracks/concrete_with_cracks_closeup_9290252_tile.tif"; 
blendAttrStr "fileTextureName2" "M:/backlot/images/textures/cracks/concrete_with_cracks_closeup_9290252_tile.tif"; 
blendAttrStr "fileTextureName1" "M:/backlot/images/textures/cracks/concrete_with_cracks_closeup_9290252_tile.tif"; 
blendAttr "scaleX" 70; 
endAttrPreset();
