// requires maya "2012";
startAttrPreset( "container" );
blendAttrStr "fileTextureName" "M:/backlot/images/textures/cracks/Crack_Pot_by_struckdumb_tile.tif"; 
blendAttrStr "fileTextureName2" "M:/backlot/images/textures/cracks/Crack_Pot_by_struckdumb_tile.tif"; 
blendAttrStr "fileTextureName1" "M:/backlot/images/textures/cracks/Crack_Pot_by_struckdumb_tile.tif"; 
blendAttr "scaleX" 70; 
endAttrPreset();
